services:
  TPDB:
    image: postgres
    container_name: TPDB
    ports:
      - 5431:5431
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=postgres  # Set the default database to docker
      - POSTGRES_USER=postgres # Create the user docker
      - POSTGRES_PASSWORD=mypswd  # Set the password for the docker user
    volumes:
      - teamProjectDB:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  teamproject:
    image: teamproject
    build: .
    container_name: teamproject
    ports:
      - 8001:8080
    networks:
      - spring-postgres
    environment:
      - DB_URL=jdbc:postgresql://TPDB:5432/docker  # Connect to the docker database
      - DB_USER=docker  # Use the docker user
      - DB_PASSWORD=pswd-docker  # Password for docker user
    depends_on:
      - TPDB
    volumes:
      - ./data:/data  
    restart: always

volumes:
  teamProjectDB:

networks:
  spring-postgres:
